package org.presentation;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sorin
 */
public class UserInterface extends javax.swing.JFrame {
    private final UInterf control;
    /**
     * Creates new form UserInterface
     * @param control
     */
    public UserInterface(UInterf control) {
        initComponents();
        start();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jClientFrame = new javax.swing.JFrame();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jClientFromAccountNo = new javax.swing.JTextField();
        jClientToAccountNo = new javax.swing.JTextField();
        jClientTransferButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jClientBillFromAccountNo = new javax.swing.JTextField();
        jClientComboUtilities = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jClientPayUtilitiesButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jClientTimePeriod = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jClientGenerateReportButton = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jAccountsListing = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jClientBillAmmount = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jClientTransferAmount = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jClientBillFromAccountNo1 = new javax.swing.JTextField();
        jClientBillFromAccountNo2 = new javax.swing.JTextField();
        jClientBillFromAccountNo3 = new javax.swing.JTextField();
        jClientBillFromAccountNo4 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jClientPayUtilitiesButton1 = new javax.swing.JButton();
        jClientPayUtilitiesButton3 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jClientBillFromAccountNo5 = new javax.swing.JTextField();
        jLoginDialog = new javax.swing.JDialog();
        jUsernameField = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLoginButton = new javax.swing.JButton();
        jLoginDialog1 = new javax.swing.JDialog();
        jLabel32 = new javax.swing.JLabel();
        jLoginDialog2 = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jAdminClientName = new javax.swing.JTextField();
        jAdminIDcardNo = new javax.swing.JTextField();
        jAdminPersNumCode = new javax.swing.JTextField();
        jAdminAddress = new javax.swing.JTextField();
        jAdminClientID = new javax.swing.JTextField();
        jAdminAccountNo = new javax.swing.JTextField();
        jAdminAccountType = new javax.swing.JTextField();
        jAdminAmmount = new javax.swing.JTextField();
        jCreateClientButton = new javax.swing.JButton();
        jGetClientAccountsButton = new javax.swing.JButton();
        jDeleteClientButton = new javax.swing.JButton();
        jAdminCreateClientAccountButton = new javax.swing.JButton();
        jAdminDeleteClientAccountButton = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jAdminTimePeriod = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jAdminGenerateButton = new javax.swing.JButton();
        jUpdateClientButton = new javax.swing.JButton();
        jAdminUpdateClientAccountButton = new javax.swing.JButton();
        jAdminClientsListingScroll = new javax.swing.JScrollPane();
        jAdminClientsListing = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jAdminClientAccountsListing = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jAdminClientUsernameField = new javax.swing.JTextField();
        jAdminClientPasswordField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jAdminClientLastName = new javax.swing.JTextField();

        jClientFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jClientFrame.setTitle("Client Panel");
        jClientFrame.setBounds(new java.awt.Rectangle(450, 300, 900, 650));
        jClientFrame.setLocation(new java.awt.Point(450, 150));
        jClientFrame.setName("clientFrame"); // NOI18N
        jClientFrame.setResizable(false);
        jClientFrame.setSize(new java.awt.Dimension(900, 650));

        jLabel11.setText("From account no.:");

        jLabel12.setText("To account no.:");

        jClientTransferButton.setText("Transfer");
        jClientTransferButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientTransferButtonMouseClicked(evt);
            }
        });

        jLabel13.setText("From account no.:");

        jClientComboUtilities.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Orange", "Vodafone", "E-ON", "RDS", "UPC", "Electrica" }));

        jLabel14.setText("Utilities bill:");

        jClientPayUtilitiesButton.setText("Pay");
        jClientPayUtilitiesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientPayUtilitiesButtonMouseClicked(evt);
            }
        });

        jLabel15.setText("Generate report for last");

        jClientTimePeriod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "7", "30", "All" }));

        jLabel16.setText("days");

        jClientGenerateReportButton.setText("Generate");
        jClientGenerateReportButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientGenerateReportButtonMouseClicked(evt);
            }
        });

        jAccountsListing.setColumns(20);
        jAccountsListing.setRows(5);
        jAccountsListing.setPreferredSize(new java.awt.Dimension(468, 638));
        jScrollPane4.setViewportView(jAccountsListing);

        jLabel24.setText("Amount:");

        jLabel25.setText("Amount:");

        jLabel26.setText("Name:");

        jLabel27.setText("Last Name");

        jLabel28.setText("ID card no.:");

        jLabel29.setText("Pers. num. code:");

        jClientBillFromAccountNo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientBillFromAccountNo1ActionPerformed(evt);
            }
        });

        jLabel30.setText("Client:");

        jClientPayUtilitiesButton1.setText("Add/Update");
        jClientPayUtilitiesButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientPayUtilitiesButton1MouseClicked(evt);
            }
        });
        jClientPayUtilitiesButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientPayUtilitiesButton1ActionPerformed(evt);
            }
        });

        jClientPayUtilitiesButton3.setText("Delete");
        jClientPayUtilitiesButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jClientPayUtilitiesButton3MouseClicked(evt);
            }
        });
        jClientPayUtilitiesButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientPayUtilitiesButton3ActionPerformed(evt);
            }
        });

        jLabel31.setText("Address:");

        javax.swing.GroupLayout jClientFrameLayout = new javax.swing.GroupLayout(jClientFrame.getContentPane());
        jClientFrame.getContentPane().setLayout(jClientFrameLayout);
        jClientFrameLayout.setHorizontalGroup(
            jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientFrameLayout.createSequentialGroup()
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClientBillFromAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jClientComboUtilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jClientBillAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jLabel14)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jClientFrameLayout.createSequentialGroup()
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jClientFrameLayout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(18, 18, 18)
                                        .addComponent(jClientTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel16)
                                        .addGap(18, 18, 18)
                                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jClientGenerateReportButton)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jClientFrameLayout.createSequentialGroup()
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel24)
                                                    .addComponent(jClientPayUtilitiesButton))
                                                .addGap(21, 21, 21))))
                                    .addGroup(jClientFrameLayout.createSequentialGroup()
                                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jClientFromAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jClientToAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel12))
                                                .addGap(18, 18, 18)
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel25)
                                                    .addComponent(jClientTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jClientTransferButton)))
                                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel27)
                                                    .addComponent(jLabel28)
                                                    .addComponent(jLabel29)
                                                    .addComponent(jLabel26)
                                                    .addComponent(jLabel31))
                                                .addGap(18, 18, 18)
                                                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jClientBillFromAccountNo4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jClientBillFromAccountNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(jClientFrameLayout.createSequentialGroup()
                                                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jClientFrameLayout.createSequentialGroup()
                                                                .addComponent(jClientBillFromAccountNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(jLabel30))
                                                            .addComponent(jClientBillFromAccountNo2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jClientPayUtilitiesButton3)
                                                            .addComponent(jClientPayUtilitiesButton1)))
                                                    .addComponent(jClientBillFromAccountNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(225, 225, 225)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jClientFrameLayout.setVerticalGroup(
            jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jClientFrameLayout.createSequentialGroup()
                .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jClientFrameLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel25))
                        .addGap(18, 18, 18)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientFromAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientToAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientTransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addComponent(jClientTransferButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jClientBillFromAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientComboUtilities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientBillAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(jClientPayUtilitiesButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jClientTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jClientGenerateReportButton))
                        .addGap(18, 18, 18)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(jClientBillFromAccountNo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(jClientPayUtilitiesButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(jClientBillFromAccountNo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jClientPayUtilitiesButton3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(jClientBillFromAccountNo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(jClientBillFromAccountNo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jClientFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jClientBillFromAccountNo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 183, Short.MAX_VALUE))
                    .addGroup(jClientFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)))
                .addContainerGap())
        );

        jLoginDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jLoginDialog.setTitle("Login");
        jLoginDialog.setBounds(new java.awt.Rectangle(450, 350, 200, 200));
        jLoginDialog.setResizable(false);
        jLoginDialog.setSize(new java.awt.Dimension(300, 190));

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Username:");

        jLabel2.setText("Password:");

        jLoginButton.setText("Login");
        jLoginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLoginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jLoginDialogLayout = new javax.swing.GroupLayout(jLoginDialog.getContentPane());
        jLoginDialog.getContentPane().setLayout(jLoginDialogLayout);
        jLoginDialogLayout.setHorizontalGroup(
            jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialogLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(26, 26, 26)
                .addGroup(jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField)
                    .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLoginDialogLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoginButton)
                .addGap(21, 21, 21))
        );
        jLoginDialogLayout.setVerticalGroup(
            jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialogLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(28, 28, 28)
                .addGroup(jLoginDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jLoginButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLoginDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jLoginDialog1.setTitle("Login");
        jLoginDialog1.setBounds(new java.awt.Rectangle(450, 350, 200, 200));
        jLoginDialog1.setResizable(false);
        jLoginDialog1.setSize(new java.awt.Dimension(300, 190));

        jLabel32.setText("Wrong username or password!");

        javax.swing.GroupLayout jLoginDialog1Layout = new javax.swing.GroupLayout(jLoginDialog1.getContentPane());
        jLoginDialog1.getContentPane().setLayout(jLoginDialog1Layout);
        jLoginDialog1Layout.setHorizontalGroup(
            jLoginDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialog1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel32)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jLoginDialog1Layout.setVerticalGroup(
            jLoginDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialog1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel32)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jLoginDialog2.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jLoginDialog2.setTitle("Login");
        jLoginDialog2.setBounds(new java.awt.Rectangle(450, 350, 200, 200));
        jLoginDialog2.setResizable(false);
        jLoginDialog2.setSize(new java.awt.Dimension(300, 190));

        jLabel33.setText("Wrong username or password!");

        javax.swing.GroupLayout jLoginDialog2Layout = new javax.swing.GroupLayout(jLoginDialog2.getContentPane());
        jLoginDialog2.getContentPane().setLayout(jLoginDialog2Layout);
        jLoginDialog2Layout.setHorizontalGroup(
            jLoginDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialog2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel33)
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jLoginDialog2Layout.setVerticalGroup(
            jLoginDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLoginDialog2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel33)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Panel");
        setBounds(new java.awt.Rectangle(400, 350, 900, 660));
        setLocation(new java.awt.Point(400, 150));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 800));

        jLabel3.setText("Client name:");

        jLabel4.setText("ID card no.:");

        jLabel5.setText("Pers. num. code:");

        jLabel6.setText("Address:");

        jLabel7.setText("Account no.:");

        jLabel8.setText("Client ID:");

        jLabel9.setText("Account type:");

        jLabel10.setText("$ ammount:");

        jCreateClientButton.setText("Create");
        jCreateClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCreateClientButtonMouseClicked(evt);
            }
        });

        jGetClientAccountsButton.setText("Get accounts");
        jGetClientAccountsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jGetClientAccountsButtonMouseClicked(evt);
            }
        });

        jDeleteClientButton.setText("Delete");
        jDeleteClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jDeleteClientButtonMouseClicked(evt);
            }
        });

        jAdminCreateClientAccountButton.setText("Create");
        jAdminCreateClientAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminCreateClientAccountButtonMouseClicked(evt);
            }
        });

        jAdminDeleteClientAccountButton.setText("Delete");
        jAdminDeleteClientAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminDeleteClientAccountButtonMouseClicked(evt);
            }
        });

        jLabel17.setText("Generate report for");

        jAdminTimePeriod.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "7", "30", "All" }));

        jLabel18.setText("days");

        jAdminGenerateButton.setText("Generate");
        jAdminGenerateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminGenerateButtonMouseClicked(evt);
            }
        });

        jUpdateClientButton.setText("Update");
        jUpdateClientButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jUpdateClientButtonMouseClicked(evt);
            }
        });

        jAdminUpdateClientAccountButton.setText("Update");
        jAdminUpdateClientAccountButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAdminUpdateClientAccountButtonMouseClicked(evt);
            }
        });

        jAdminClientsListingScroll.setPreferredSize(new java.awt.Dimension(420, 420));

        jAdminClientsListing.setColumns(20);
        jAdminClientsListing.setRows(5);
        jAdminClientsListingScroll.setViewportView(jAdminClientsListing);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(420, 450));

        jAdminClientAccountsListing.setColumns(20);
        jAdminClientAccountsListing.setRows(5);
        jAdminClientAccountsListing.setPreferredSize(new java.awt.Dimension(420, 450));
        jScrollPane1.setViewportView(jAdminClientAccountsListing);

        jLabel19.setText("Client:");

        jLabel20.setText("Account:");

        jLabel21.setText("Client username:");

        jLabel22.setText("Client password:");

        jLabel23.setText("Last name:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel8))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jAdminClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jLabel7))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAdminClientID, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jAdminAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jAdminClientName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jAdminAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(90, 90, 90)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel20)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jAdminAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(33, 33, 33)
                                        .addComponent(jAdminCreateClientAccountButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jAdminUpdateClientAccountButton)
                                        .addGap(1, 1, 1)
                                        .addComponent(jAdminDeleteClientAccountButton)))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jAdminIDcardNo))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jAdminPersNumCode, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jAdminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel19)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jGetClientAccountsButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCreateClientButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jDeleteClientButton)
                                                .addGap(52, 52, 52))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jUpdateClientButton)
                                        .addGap(101, 101, 101))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jAdminClientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jAdminClientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jAdminClientsListingScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(248, 248, 248)
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(jAdminTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jAdminGenerateButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jAdminClientsListingScroll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jGetClientAccountsButton)
                                    .addComponent(jCreateClientButton)
                                    .addComponent(jDeleteClientButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jUpdateClientButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4))
                                        .addGap(55, 55, 55))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jAdminIDcardNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAdminPersNumCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jAdminAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(21, 21, 21)))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel23))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jAdminClientName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jAdminClientLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdminClientID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminAmmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminCreateClientAccountButton)
                    .addComponent(jAdminDeleteClientAccountButton)
                    .addComponent(jAdminUpdateClientAccountButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAdminClientUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jAdminClientPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jAdminTimePeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jAdminGenerateButton))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLoginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLoginButtonMouseClicked
        // TODO add your handling code here:
        control.loginButtonClicked();
    }//GEN-LAST:event_jLoginButtonMouseClicked

    private void jGetClientAccountsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jGetClientAccountsButtonMouseClicked
        // TODO add your handling code here:
        control.adminGetClientAccountsButtonClicked();
    }//GEN-LAST:event_jGetClientAccountsButtonMouseClicked

    private void jCreateClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCreateClientButtonMouseClicked
        // TODO add your handling code here:
        control.adminCreateClientButtonClicked();
    }//GEN-LAST:event_jCreateClientButtonMouseClicked

    private void jUpdateClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jUpdateClientButtonMouseClicked
        // TODO add your handling code here:
        control.adminUpdateClientButtonClicked();
    }//GEN-LAST:event_jUpdateClientButtonMouseClicked

    private void jDeleteClientButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jDeleteClientButtonMouseClicked
        // TODO add your handling code here:
        control.adminDeleteClientButtonClicked();
    }//GEN-LAST:event_jDeleteClientButtonMouseClicked

    private void jAdminCreateClientAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminCreateClientAccountButtonMouseClicked
        // TODO add your handling code here:
        control.adminCreateClientAccountButtonClicked();
    }//GEN-LAST:event_jAdminCreateClientAccountButtonMouseClicked

    private void jAdminUpdateClientAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminUpdateClientAccountButtonMouseClicked
        // TODO add your handling code here:
        control.adminUpdateClientAccountButtonClicked();
    }//GEN-LAST:event_jAdminUpdateClientAccountButtonMouseClicked

    private void jAdminDeleteClientAccountButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminDeleteClientAccountButtonMouseClicked
        // TODO add your handling code here:
        control.adminDeleteClientAccountButtonClicked();
    }//GEN-LAST:event_jAdminDeleteClientAccountButtonMouseClicked

    private void jAdminGenerateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAdminGenerateButtonMouseClicked
        // TODO add your handling code here:
        control.adminGenerateReportButtonClicked();
    }//GEN-LAST:event_jAdminGenerateButtonMouseClicked

    private void jClientGenerateReportButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientGenerateReportButtonMouseClicked
        // TODO add your handling code here:
        control.clientGenerateReportButtonClicked();
    }//GEN-LAST:event_jClientGenerateReportButtonMouseClicked

    private void jClientPayUtilitiesButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientPayUtilitiesButtonMouseClicked
        // TODO add your handling code here:
        control.clientPayUtilitiesButtonClicked();
    }//GEN-LAST:event_jClientPayUtilitiesButtonMouseClicked

    private void jClientTransferButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientTransferButtonMouseClicked
        // TODO add your handling code here:
        control.clientTransferButtonClicked();
    }//GEN-LAST:event_jClientTransferButtonMouseClicked

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jClientBillFromAccountNo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientBillFromAccountNo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientBillFromAccountNo1ActionPerformed

    private void jClientPayUtilitiesButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientPayUtilitiesButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientPayUtilitiesButton1MouseClicked

    private void jClientPayUtilitiesButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientPayUtilitiesButton1ActionPerformed
        // TODO add your handling code here:
        control.clientUpdateClientButtonClicked();
    }//GEN-LAST:event_jClientPayUtilitiesButton1ActionPerformed

    private void jClientPayUtilitiesButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientPayUtilitiesButton3ActionPerformed
        // TODO add your handling code here:
        control.clientDeleteClientButtonClicked();
    }//GEN-LAST:event_jClientPayUtilitiesButton3ActionPerformed

    private void jClientPayUtilitiesButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jClientPayUtilitiesButton3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jClientPayUtilitiesButton3MouseClicked

    
    public final void start() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("System".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jAccountsListing;
    private javax.swing.JTextField jAdminAccountNo;
    private javax.swing.JTextField jAdminAccountType;
    private javax.swing.JTextField jAdminAddress;
    private javax.swing.JTextField jAdminAmmount;
    private javax.swing.JTextArea jAdminClientAccountsListing;
    private javax.swing.JTextField jAdminClientID;
    private javax.swing.JTextField jAdminClientLastName;
    private javax.swing.JTextField jAdminClientName;
    private javax.swing.JTextField jAdminClientPasswordField;
    private javax.swing.JTextField jAdminClientUsernameField;
    private javax.swing.JTextArea jAdminClientsListing;
    private javax.swing.JScrollPane jAdminClientsListingScroll;
    private javax.swing.JButton jAdminCreateClientAccountButton;
    private javax.swing.JButton jAdminDeleteClientAccountButton;
    private javax.swing.JButton jAdminGenerateButton;
    private javax.swing.JTextField jAdminIDcardNo;
    private javax.swing.JTextField jAdminPersNumCode;
    private javax.swing.JComboBox jAdminTimePeriod;
    private javax.swing.JButton jAdminUpdateClientAccountButton;
    private javax.swing.JTextField jClientBillAmmount;
    private javax.swing.JTextField jClientBillFromAccountNo;
    private javax.swing.JTextField jClientBillFromAccountNo1;
    private javax.swing.JTextField jClientBillFromAccountNo2;
    private javax.swing.JTextField jClientBillFromAccountNo3;
    private javax.swing.JTextField jClientBillFromAccountNo4;
    private javax.swing.JTextField jClientBillFromAccountNo5;
    private javax.swing.JComboBox jClientComboUtilities;
    private javax.swing.JFrame jClientFrame;
    private javax.swing.JTextField jClientFromAccountNo;
    private javax.swing.JButton jClientGenerateReportButton;
    private javax.swing.JButton jClientPayUtilitiesButton;
    private javax.swing.JButton jClientPayUtilitiesButton1;
    private javax.swing.JButton jClientPayUtilitiesButton3;
    private javax.swing.JComboBox jClientTimePeriod;
    private javax.swing.JTextField jClientToAccountNo;
    private javax.swing.JTextField jClientTransferAmount;
    private javax.swing.JButton jClientTransferButton;
    private javax.swing.JButton jCreateClientButton;
    private javax.swing.JButton jDeleteClientButton;
    private javax.swing.JButton jGetClientAccountsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoginButton;
    private javax.swing.JDialog jLoginDialog;
    private javax.swing.JDialog jLoginDialog1;
    private javax.swing.JDialog jLoginDialog2;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JButton jUpdateClientButton;
    private javax.swing.JTextField jUsernameField;
    // End of variables declaration//GEN-END:variables

    public void showLoginWindow(){
        this.jLoginDialog.setVisible(true);
    }
    
    public void showClientWindow(){
        this.jLoginDialog.setVisible(false);
        this.jLoginDialog1.setVisible(false);
        this.jLoginDialog2.setVisible(false);
        this.setVisible(false);
        this.jClientFrame.setVisible(true);
    }
    public void showAdminWindow(){
        this.jLoginDialog.setVisible(false);
        this.jLoginDialog1.setVisible(false);
        this.jLoginDialog2.setVisible(false);
        this.jClientFrame.setVisible(false);
        this.setVisible(true);
    }
    
    public void showLoginWindow1(){
        this.jLoginDialog1.setVisible(true);
    }
    
    public void showLoginWindow2(){
        this.jLoginDialog2.setVisible(true);
    }
    
    public String getUsernameField(){
        return this.jUsernameField.getText();
    }
    public String getPasswordField(){
        return this.jPasswordField.getText();
    }
    public String getAdminClientName(){
        return this.jAdminClientName.getText();
    }
    public String getAdminClientIDcardNo(){
        return this.jAdminIDcardNo.getText();
    }
    public String getAdminClientPersNumCode(){
        return this.jAdminPersNumCode.getText();
    }
    public String getAdminClientAddress(){
        return this.jAdminAddress.getText();
    }
    public String getAdminClientID(){
        return this.jAdminClientID.getText();
    }
    public String getAdminClientAccountNo(){
        return this.jAdminAccountNo.getText();
    }
    public String getAdminClientAccountType(){
        return this.jAdminAccountType.getText();
    }
    public String getAdminClientAmmount(){
        return this.jAdminAmmount.getText();
    }
    public String getAdminReportTimePeriod(){
        return this.jAdminTimePeriod.getSelectedItem().toString();
    }
    public String getClientFromAccountNo(){
        return this.jClientFromAccountNo.getText();
    }
    public String getClientToAccountNo(){
        return this.jClientToAccountNo.getText();
    }
    public String getClientBillFromAccountNo(){
        return this.jClientBillFromAccountNo.getText();
    }
    public String getClientSelectedUtilityBill(){
        return (String) this.jClientComboUtilities.getSelectedItem();
    }
    public String getClientReportTimePeriod(){
        return (String) this.jClientTimePeriod.getSelectedItem();
    }
    public void setClientAccountsListing(String account){
        this.jAccountsListing.setText(account);
    }
    public void setAdminClientsListing(String clients){
        this.jAdminClientsListing.setText(clients);
    }
    public void setAdminClientAccountsListing(String accounts){
        this.jAdminClientAccountsListing.setText(accounts);
    }
    public String getAdminClientUsername(){
        return this.jAdminClientUsernameField.getText();
    }
    public String getAdminClientPassword(){
        return this.jAdminClientPasswordField.getText();
    }
    public String getAdminClientLastName(){
        return this.jAdminClientLastName.getText();
    }
    public String getClientBillAmount(){
        return this.jClientBillAmmount.getText();
    }
    public String getClientTransferAmount(){
        return this.jClientTransferAmount.getText();
    }
    
    
    public String getClientFromAccountNo1(){
        return this.jClientBillFromAccountNo1.getText();
    }
    public void setClientFromAccountNo1(String accounts){
        this.jClientBillFromAccountNo1.setText(accounts);
    }
    
    public String getClientFromAccountNo2(){
        return this.jClientBillFromAccountNo2.getText();
    }
    public void setClientFromAccountNo2(String accounts){
        this.jClientBillFromAccountNo2.setText(accounts);
    }
    
    public String getClientFromAccountNo3(){
        return this.jClientBillFromAccountNo3.getText();
    }
    public void setClientFromAccountNo3(String accounts){
        this.jClientBillFromAccountNo3.setText(accounts);
    }
    
    public String getClientFromAccountNo4(){
        return this.jClientBillFromAccountNo4.getText();
    }
    public void setClientFromAccountNo4(String accounts){
        this.jClientBillFromAccountNo4.setText(accounts);
    }
    
    public String getClientFromAccountNo5(){
        return this.jClientBillFromAccountNo5.getText();
    }
    public void setClientFromAccountNo5(String accounts){
        this.jClientBillFromAccountNo5.setText(accounts);
    }
}
